version: '3.6'

services:
  rdmo:
    image: rdmo
    build:
      dockerfile: Dockerfile
      context: ./
    environment:
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - static_volume:/code/staticfiles
    expose:
      - "8080"
    networks:
      - nginx-proxy
    links:
      - database
    restart: unless-stopped

  reverse-proxy:
    image: nginx:1.19
    expose:
      - "1239"
    ports:
      - "1239:1239"
    secrets:
      - rdmo_htpasswd
    environment:
      - NGINX_PORT=1239
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - static_volume:/code/rdmo/staticfiles
      - ./nginx-staging/nginx.conf:/etc/nginx/nginx.conf
    links:
      - rdmo
    networks:
      - nginx-proxy
    restart: unless-stopped

  database:
    image: mariadb:10.5
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    expose:
      - "3306"
    networks:
      - nginx-proxy
    restart: unless-stopped

volumes:
  static_volume: {}
  database:

networks:
  nginx-proxy:
    external:
      name: nginx-proxy

secrets:
  rdmo_mysql.conf:
    file: ${HOME}/config/rdmo_mysql.conf
  rdmo_htpasswd:
    file: ${HOME}/config/rdmo_htpasswd
