version: '3.6'

services:
  rdmo:
    image: rdmo
    build:
      dockerfile: Dockerfile
      context: ./
    environment:
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOST_1=${ALLOWED_HOST_1}
      - FROM_EMAIL=${FROM_EMAIL}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - ADMIN_1=${ADMIN_1}
      - ADMIN_2=${ADMIN_2}
    volumes:
      - static_volume:/code/staticfiles
      - media:/code/media_root
      - ./theme/:/code/theme
    expose:
      - "8080"
    networks:
      - nginx-proxy
    links:
      - database
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: ${FLUENTD_RDMO_TAG}
    restart: unless-stopped

  reverse-proxy:
    image: nginx:1.19
    expose:
      - "1239"
    environment:
      - NGINX_PORT=1239
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${VIRTUAL_HOST}
    volumes:
      - static_volume:/code/rdmo/staticfiles
      - ./nginx-staging/nginx.conf:/etc/nginx/nginx.conf
    links:
      - rdmo
    networks:
      - nginx-proxy
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: ${FLUENTD_REVERSEPROXY_TAG}
    restart: unless-stopped

  database:
    image: mariadb:10.5
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - database:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - nginx-proxy
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: ${FLUENTD_DB_TAG}
    restart: unless-stopped

volumes:
  static_volume: {}
  media: {}
  database: {}

networks:
  nginx-proxy:
    external:
      name: nginx-proxy
